name: birthday_planer
description: safe gifts for friends and get reminded about their birthdays.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  provider: ^6.0.0
  confetti: ^0.6.0

  path_provider: ^2.0.11
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  contacts_service: ^0.6.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  isar_generator: ^3.1.0
  build_runner: any


flutter:
  uses-material-design: true